/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unir.laboratorio_1;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupDistribuidor = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ComboTipoMedicamento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextNombreMedicamento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CheckPrincipal = new javax.swing.JCheckBox();
        CheckSecundaria = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        BotonBorrar = new javax.swing.JButton();
        BotonConfirmar = new javax.swing.JButton();
        RadioCofarma = new javax.swing.JRadioButton();
        RadioEmpsephar = new javax.swing.JRadioButton();
        RadioCemefar = new javax.swing.JRadioButton();

        ButtonGroupDistribuidor.add(RadioCofarma);
        ButtonGroupDistribuidor.add(RadioEmpsephar);
        ButtonGroupDistribuidor.add(RadioCemefar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA DE PEDIDOS");

        ComboTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Analgesico", "Analeptico", "Anestesico", "Antiacido", "Antidepresivo", "Antibiotico" }));

        jLabel2.setText("Tipo de medicamento:");

        jLabel3.setText("Nombre del medicamento:");

        jLabel4.setText("Cantidad:");

        TextCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCantidadActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre del distribuidor:");

        CheckPrincipal.setText("Farmacia Principal");

        CheckSecundaria.setText("Farmacia Secundaria");

        jLabel6.setText("Sucursal:");

        BotonBorrar.setText("Borrar");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonConfirmar.setText("Confirmar");
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        RadioCofarma.setText("Cofarma");

        RadioEmpsephar.setText("Empsephar ");

        RadioCemefar.setText("Cemefar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboTipoMedicamento, 0, 200, Short.MAX_VALUE)
                            .addComponent(TextCantidad)
                            .addComponent(TextNombreMedicamento)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioCofarma)
                                    .addComponent(RadioEmpsephar)
                                    .addComponent(RadioCemefar))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckPrincipal)
                                    .addComponent(CheckSecundaria))
                                .addGap(76, 76, 76))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(BotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextNombreMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboTipoMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RadioCofarma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioEmpsephar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioCemefar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckPrincipal)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckSecundaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonBorrar)
                    .addComponent(BotonConfirmar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCantidadActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        this.TextNombreMedicamento.setText("");
        this.TextCantidad.setText("");
        this.ButtonGroupDistribuidor.clearSelection();
        this.ComboTipoMedicamento.setSelectedIndex(0);
        this.CheckPrincipal.setSelected(false);
        this.CheckSecundaria.setSelected(false);
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private static boolean isAlphaNumeric(String s) {
        return s != null && s.isEmpty()!=true && s.isBlank()!=true && s.matches("^[a-zA-Z0-9]*$");
    }
    
    private static boolean isNumeric(String s) {
        try {
            Integer.parseInt(s);
            return true;
	} catch (NumberFormatException nfe){
            return false;
	}
    }
    
    private String getSelectedButton(javax.swing.ButtonGroup buttonGroup)
    {  
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
        int error=0;
        String description = "";
        String direccionSucursalPrincipal="Calle de la Rosa n. 28";
        String direccionSucursalSecundaria="Calle Alcazabilla n. 3";
        
        if(!isAlphaNumeric(this.TextNombreMedicamento.getText())){
            error=1;
            description ="El nombre del medicamento esta incorrecto";
        }
        
        if(this.ComboTipoMedicamento.getSelectedIndex()==0){
            error=1;
            description ="No se ha seleccionado un tipo de medicamento";
        }
        
        if(!isNumeric(this.TextCantidad.getText())){
            error=1;
            description ="El cantidad no es un numero entero positivo";
        }
        
        //Validar Radio Buttons
        if(this.getSelectedButton(this.ButtonGroupDistribuidor)==null){
            error=1;
            description ="No se ha seleccionado un distribuidor";
        }
        /*****/
        
        // validar checks
        int contSucursal=0;
        if(!this.CheckPrincipal.isSelected()){
            contSucursal++;
        }
        if(!this.CheckSecundaria.isSelected()){
            contSucursal++;
        }
        if(contSucursal==2){
            error=1;
            description ="No se ha seleccionado una sucursal";
        }
        /*****/
        
        JFrame ventana = new JFrame();
        
        if(error==1){
            JLabel LabelDescription = new javax.swing.JLabel();
            LabelDescription.setText(description);
            Dimension size = LabelDescription.getPreferredSize();
            LabelDescription.setBounds(130, 140, size.width, size.height);
            LabelDescription.setBackground(Color.red);
            LabelDescription.setVisible(true);
            ventana.add(LabelDescription);
        }else{
            
            JLabel LabelDistribuidor = new javax.swing.JLabel();
            JLabel LabelMedicamento = new javax.swing.JLabel();
            JLabel LabelDireccion = new javax.swing.JLabel();
            JButton BotonConfirmarPedido = new javax.swing.JButton("Enviar Pedido");
            JButton BotonCancelarPedido = new javax.swing.JButton("Cancelar Pedido");
            
            BotonConfirmarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    System.out.println("Pedido Enviado");
                    ventana.setVisible(false);
                    BotonBorrarActionPerformed(evt);
                }
            });
            
            BotonCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ventana.setVisible(false);
                    BotonBorrarActionPerformed(evt);
                }
            });
            
            
            LabelDistribuidor.setText("Pedido al distribuidor "+this.getSelectedButton(this.ButtonGroupDistribuidor));
            LabelMedicamento.setText(this.TextCantidad.getText()+" unidades del "+this.TextNombreMedicamento.getText()+" "+this.ComboTipoMedicamento.getSelectedItem().toString());
            
            if(this.CheckPrincipal.isSelected() && contSucursal==1){
                LabelDireccion.setText("Para la farmacia situada en la "+ direccionSucursalPrincipal);
            }
            
            if(this.CheckSecundaria.isSelected() && contSucursal==1){
                LabelDireccion.setText("Para la farmacia situada en la "+ direccionSucursalSecundaria);
            }
            
            if(contSucursal==0){
                LabelDireccion.setText("<html>Para la farmacia situada en la  "+ direccionSucursalPrincipal+" <br/> y para la situada en la  "+direccionSucursalSecundaria+"</html>");
            }
            
            
            Dimension size = LabelDistribuidor.getPreferredSize();
            LabelDistribuidor.setBounds(130, 140, size.width, size.height);
            LabelDistribuidor.setVisible(true);
            
            size = LabelMedicamento.getPreferredSize();
            LabelMedicamento.setBounds(130, 160, size.width, size.height);
            LabelMedicamento.setVisible(true);
            
            size = LabelDireccion.getPreferredSize();
            LabelDireccion.setBounds(130, 180, size.width, size.height);
            LabelDireccion.setVisible(true);
            
            size = BotonCancelarPedido.getPreferredSize();
            BotonCancelarPedido.setBounds(100, 250, size.width, size.height);
            BotonCancelarPedido.setVisible(true);
            
            size = BotonConfirmarPedido.getPreferredSize();
            BotonConfirmarPedido.setBounds(260,250 , size.width, size.height);
            BotonConfirmarPedido.setVisible(true);
            
            ventana.add(LabelDistribuidor);
            ventana.add(LabelMedicamento);
            ventana.add(LabelDireccion);
            
            ventana.add(BotonCancelarPedido);
            ventana.add(BotonConfirmarPedido);
            
        }
        
        ventana.setLayout(null);
        ventana.setSize(476, 348);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.ButtonGroup ButtonGroupDistribuidor;
    private javax.swing.JCheckBox CheckPrincipal;
    private javax.swing.JCheckBox CheckSecundaria;
    private javax.swing.JComboBox<String> ComboTipoMedicamento;
    private javax.swing.JRadioButton RadioCemefar;
    private javax.swing.JRadioButton RadioCofarma;
    private javax.swing.JRadioButton RadioEmpsephar;
    private javax.swing.JTextField TextCantidad;
    private javax.swing.JTextField TextNombreMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
